- README.md
Addresses #18.
Also: suggests using Python 3.9; drops `sudo` when installing tox; and hints a syntax-highlighting mode.
(The last one is probably silly because GitHub deems that there isn't much to highlight...)
> Suggest using a virtualenv

- .github/workflows/test.yml
- swagger_server/messaging/message_queue_producer.py
- swagger_server/test/test_topology_controller.py
See issue #14.
This PR removes the two errors flake8 reported:
- `undefined name 'Object'`
- `undefined name 'Image'`
Also updates CI configuration so that this class of flake8 errors are actually treated as errors.  CI will error out if flake8 detects such errors again.
We can run `python ./swagger_server/messaging/message_queue_producer.py` as a smoke test now, if RabbitMQ is running.
> Address some flake8 errors

- .github/workflows/test.yml
- swagger_server/controllers/topology_controller.py
- swagger_server/messaging/rpc_queue_producer.py
See issue #31.
Once `RpcProducer`  is instantiated, it will keep sending keep-alive pings to the message queue.  This PR adds an `RpcProducer.stop()` method which will signal that it should shut down, and uses the method from the test suite so that the test suite can terminate instead of continuing to run the thread for no good reason.
> Exit test suite when done

- .dockerignore
- .github/workflows/checks.yml
- .github/workflows/images.yml
- Dockerfile
Issue is #80. Changes:
- Lint Dockerfile with hadolint.
- Add hadolint as a CI step.
- Ignore some directories (venv, .git, .tox) when building images.
- Use a smaller base image. On a quick check with `podman build`, I now get an image of 197 MB, whereas image size when using the `python:3.9.6-buster` base image is 975 MB.
- Disable building/publishing container images on pull requests. Images will be built and published only on commits to main, or when a tag (meaning, a release) has been pushed.
> Lint Dockerfile with hadolint

- swagger_server/utils/db_utils.py
This converts all keys to string for mongodb read and write, because Mongodb requires keys to be string.
> convert mongo key to str

- swagger_server/__main__.py
This enables saving logs to file.
> allow saving log to file

- swagger_server/messaging/topic_queue_consumer.py
Resolves: https://github.com/atlanticwave-sdx/sdx-lc/issues/109
Sometimes topic queue consumer receives RabbitMQ message from wrong OXP. So update with an empty queue name, and later bind it to a unique queue. As suggested in [this](https://github.com/atlanticwave-sdx/sdx-lc/issues/109#issuecomment-2035178647) comment, this is also used by RabbitMQ tutorial.
> Use empty queue name

- .github/workflows/test.yml
- README.md
- sdx_lc/test/test_topology_controller.py
- tox.ini
Resolves #121. Changes:
- Use tox-docker to spin up services when testing with `tox`.
- Update testing instructions
> Use tox-docker

- env.template
Use the LC domain as MQ routing key to avoid confusion.
> Update SUB_TOPIC to be same as SDXLC_DOMAIN

- .github/workflows/test.yml
- compose.yml
- env.template
- sdx_lc/__main__.py
- sdx_lc/controllers/topology_controller.py
- sdx_lc/messaging/topic_queue_consumer.py
- tox.ini
Resolves #137: gets rid of some environment variables (`SUB_QUEUE`, `SUB_EXCHANGE`, `SUB_TOPIC`), and use defaults instead.
We do not need a queue name. We do need an exchange name (which would be just "connection") to receive connection/link messages published by SDX-Controller. SUB_TOPIC is not really ever used.
This is stacked on top of #142; please review that PR first.
> Simplify message queue configuration

- .github/workflows/test.yml
- README.md
- compose.yml
- env.template
- sdx_lc/utils/db_utils.py
- tox.ini
Resolves #147 by splitting `MONGODB_CONNSTRING` to `MONGO_HOST`, `MONGO_PORT`, `MONGO_USER`, and `MONGO_PASS`.
Similar to https://github.com/atlanticwave-sdx/sdx-controller/pull/292.
> Use tox-docker `expose` directive

- sdx_lc/jobs/pull_topo_changes.py
Fix #144 
This change adds a minimal enhancement on the error handling process while pulling the topology from OXP and the OXP is not accessible (e.g., OXP is still booting up or during a maintenance window) -- resulting in ConnectionReset (not previously handled).
Local tests following the [guidelines for single server deployment](https://sdx-docs.readthedocs.io/en/latest/sdx_deploy_single_server.html) showed this fix was effective to avoid exceptions and crash of the topology pulling script.
> Add error handling for connection reset when pulling the topology and the OXP is still booting up

- sdx_lc/models/link.py
- sdx_lc/models/node.py
- sdx_lc/models/port.py
- sdx_lc/swagger/swagger.yaml
- sdx_lc/test/test_connection_controller.py
- sdx_lc/test/test_link_controller.py
- sdx_lc/test/test_node_controller.py
- sdx_lc/test/test_topology_controller.py
Fix #157 
- Changed attributes on the swagger/openapi yaml file to comply with Topology Data Model spec 2.0.0
- Removed examples from the swagger spec (easy to maintain)
- port model updated to add new fields (mtu and type)
- updated unit tests to adjust for the new openapi definition.
- renamed `private_attributes` to `private` (removed from Node, which does not have any attribute allowed to be private)
> Change SDX-LC swagger spec to comply with topology spec 2.0.0

- sdx_lc/swagger/swagger.yaml
Rename Topology.Node.Port.private_attributes to private, which was left behind.
> Rename private_attributes -> private on swagger

- .github/workflows/test.yml
- .mailmap
- pyproject.toml
Similar to https://github.com/atlanticwave-sdx/sdx-controller/pull/321:
- Use flit as the build backend.
- Bump version up to `3.0.0.dev0`.
- Require Python >= 3.9.
- Remove Python 3.8 from the test matrix, and add Python 3.11 and 3.12 instead.
- Add Italo to author's list.
- Add a `.mailmap`.
This time I did a smoke test with `docker compose up --build`. :-)
> Housekeeping updates

- sdx_lc/jobs/pull_topo_changes.py
Fix #166 
As described on Issue #166, there was conditions where the pull topology routine were being executing in a loop, one request after the other very massively, and possibility impacting the OXP. With the proposed change, the sleep interval will happen at the being of the pull topology routine, so any failure when fetching the topology from OXP will then have a interval before next request (as already defined in OXP_PULL_INTERVAL env var)
> Change sleep call to be executed at the begin of pull topology routine

- sdx_lc/jobs/pull_topo_changes.py
As described on PR #167, there was one missing `time.sleep` call pending..
> Missing change from PR 167

- sdx_lc/utils/db_utils.py
Setting pymongo to INFO level, so we don't get noisy debug messages from pymongo when we use DEBUG level logging for LC.
> Change pymongo logging to INFO level

- sdx_lc/controllers/topology_controller.py
- sdx_lc/jobs/pull_topo_changes.py
- sdx_lc/swagger/swagger.yaml
Add an API to query the timestamp for latest topology pulling from OXP.
When updating the latest topology, LC will save the timestamp to the db. The timestamp is in seconds, e.g., 1734837838.
> Add topo timestamp api

- sdx_lc/controllers/topology_controller.py
- sdx_lc/handlers/sdx_controller_msg_handler.py
- sdx_lc/jobs/pull_topo_changes.py
- sdx_lc/messaging/topic_queue_consumer.py
Resolves: https://github.com/atlanticwave-sdx/sdx-lc/issues/162
After placing the connection, LC will send the OXP's HTTP response to SDX controller via MQ, so SDX controller will update the connection to include the OXP's response.
For simplicity, it may not make sense to create a separate queue just for sending the OXP connection response, so I repurposed the "topo" queue to do both topology reporting and OXP response reporting. The queue name is changed to "oxp_update", which may make more sense.
> Propagate oxp response to sdx controller

- sdx_lc/app.py
- sdx_lc/utils/db_utils.py
Fix #176 
As discussed during the All Hands Meeting, it would be nice if we have means to change the log level of the SDX components for production environment. In production, having the log level hardcoded to DEBUG is not recommended. With this PR, the SDX-LC operator can now set an environment variable called `LOG_LEVEL` and change this behavior.
For backward compatibility, the LOG_LEVEL defaults to "DEBUG" just as current behavior.
> Adding log level configuration from env variable

- sdx_lc/handlers/sdx_controller_msg_handler.py
- sdx_lc/jobs/pull_topo_changes.py
This PR introduces the capability of supporting authenticated OXPs, based on HTTP Basic Authentication. Future work can be developed to also add extra authentication mechanism. However the current implementation will be enough to support Kytos use case in production.
> Add support for authenticated OXPO

- sdx_lc/swagger/swagger.yaml
Fix #170 
According to the last All Hands Meeting discussion regarding the allowed range for Longitude Location object, this PR modifies the allowed values.
> Change min and max allowed values for longitude

- sdx_lc/swagger/swagger.yaml
Fix #165 
According to the Topology data model spec, the iso3166_2_lvl4 should be composed by a 2 alphanumeric  characters representing the country code + "-" + up to three alpha chars obtained from national sources and stems from coding systems already in use in the country concerned. The regex code for this attribute was correct, but the min and max length were not comply with the spec.
This PR fixes the min and max length for the iso3166_2_lvl4 attribute.
> Fix min and max length for iso3166_2_lvl4 attribute

- sdx_lc/handlers/sdx_controller_msg_handler.py
Resolves: https://github.com/atlanticwave-sdx/sdx-lc/issues/184
Include "lc_domain" in the RPC response so SDX controller can know which LC sent back the rpc response.
> Include lc name in rpc response

- sdx_lc/swagger/swagger.yaml
Fix #178 
This is a very simple PR which adds the entities attribute into swagger validation schema. Since LC will just forward the information received from OXP to SDX-Controller, no additional changes were necessary.
Kytos SDX Napp is already capable of sending the `entities` attribute (https://github.com/atlanticwave-sdx/kytos-sdx) and work is being done on sdx-continuous-development repo to also have those tests (https://github.com/atlanticwave-sdx/sdx-continuous-development/issues/121).
> Adding validation rules for entities attributes on swagger

- sdx_lc/handlers/sdx_controller_msg_handler.py
Fix #188 
This PR adds a three main improvements:
1. enhance logging with info received from OXP
2. adding information about operation being reported from LC to Controller
3. send information from OXP response to controller
The modifications are backward compatible and  won't impact the SDX-Controller, because none of the existing attributes were actually changed. The `oxp_response` used to be "None" and now will contain data from OXP.
> Enhance information from OXP responses on the logging and to the controller

- CHANGELOG.md
- pyproject.toml
- sdx_lc/handlers/sdx_controller_msg_handler.py
- sdx_lc/messaging/topic_queue_consumer.py
Fix #192 
- Enhanced error handler when processing OXP response to avoid non-json content from breaking the code
- Augmented general error handler when processing rabbitmq messages to avoid breaking the consumer
With the fix applied and following the steps documented on the issue, we get the following result:
```
$ docker compose exec -it mininet curl -s -X POST -H 'Content-type: application/json' http://sdx-controller:8080/SDX-Controller/l2vpn/1.0 -d '{"name": "vlan test", "endpoints": [{"port_id": "urn:sdx:port:ampath.net:Ampath3:50", "vlan": "999"}, {"port_id": "urn:sdx:port:sax.net:Sax01:50", "vlan": "999"}]}'
{
"reason": "Connection published",
"service_id": "1e123abc-11f0-4a42-bb20-af6234dc2f33",
"status": "under provisioning"
}
$ ./show-sdx-controller.sh l2vpn
ID …
```
> Augmented error handling on rabbitmq consumer thread
